feat(builder): allow script to build multiple resources
Stuyk/altv-typescript pull request #14
Opened 2023-05-22 19:34 UTC by CENSOR1337

I would greatly appreciate any suggestions or improvements you might have =D

2023-05-23 17:56 UTC, Stuyk requested changes

2023-05-23 17:56 UTC, Stuyk commented on scripts/compiler.js
> +async function BuildTargetResource(name) {
`BuildTargetResource` should be `buildTargetResource`

It is not a class and not invoked with `new` so common convention is `camelCase`

2023-05-23 17:56 UTC, Stuyk commented on scripts/compiler.js
> +    BuildTargetResource(resource);
Update name

2023-05-23 17:56 UTC, Stuyk commented on scripts/copy.js
> +async function CopyResourceAssets(name) {
camelCase for function name

2023-05-23 17:56 UTC, Stuyk commented on scripts/copy.js
> +    CopyResourceAssets(resource);
camelCase for function name

2023-05-23 17:56 UTC, Stuyk commented on scripts/shared.js
> +export const resources = [
Preferably we shouldn't be specifying what resources to compile.

Instead I suggest we take a look at the `.toml` file for the server and extract resources that way.

If we need to ignore certain folders from compiling maybe consider adding a file inside of a resource folder called `.nocompile` or `.ignore` or something of the sort and immediately skip that resource entirely if it is present.

2023-05-23 17:56 UTC, Stuyk commented on scripts/transform.js
> +async function TransformResource(name) {
`camelCase`

2023-05-23 17:56 UTC, Stuyk commented on scripts/transform.js
> +    TransformResource(resource);
`camelCase`

2023-05-23 19:17 UTC, CENSOR1337 commented
Hey, thanks for your advice!, I've made the changes based on all your suggestions. =D

[refactor(builder): using camelCase for function name](https://github.com/Stuyk/altv-typescript/pull/14/commits/6b35d4f2c10973101250b8114d639f4f0893da97) https://github.com/Stuyk/altv-typescript/pull/14/commits/6b35d4f2c10973101250b8114d639f4f0893da97


[refactor: reference target resource from server config](https://github.com/Stuyk/altv-typescript/pull/14/commits/30f91841168829b2056cc2c4eb51b58abb7a9c22) https://github.com/Stuyk/altv-typescript/pull/14/commits/30f91841168829b2056cc2c4eb51b58abb7a9c22

2023-05-23 22:34 UTC, Stuyk commented
Looks much better. Only thing left is documenting it into the `README` file.

2023-05-24 06:56 UTC, CENSOR1337 commented
> Looks much better. Only thing left is documenting it into the `README` file.

Updated the readme! Let me know what you think. Thanks!

2023-05-24 12:18 UTC, Stuyk approved these changes

2023-05-24 12:18 UTC, merged